/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship_emblem = IconData(0xea97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wolf_howl = IconData(0xeae8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space_shuttle = IconData(0xf197, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebel = IconData(0xf1d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empire = IconData(0xf1d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_order = IconData(0xf2b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_order_alt = IconData(0xf50a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData galactic_republic = IconData(0xf50c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData galactic_senate = IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jedi_order = IconData(0xf50e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData old_republic = IconData(0xf510, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sith = IconData(0xf512, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trade_federation = IconData(0xf513, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jedi = IconData(0xf669, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData journal_whills = IconData(0xf66a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d6 = IconData(0xf6d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
